server:
  port: 9505

mybatis:
    typeAliasesPackage: taru.luo.graduation.entity
    mapperLocations: classpath:mapper/*.xml

spring:
  application:
    name: taru
  datasource:
    url: jdbc:mysql://120.78.156.24:3306/graduation?useUnicode=true
    username: myuser
    password: 123456



